### ISSUE TITLE
eslint front-end

### ISSUE THREAD

**Issue by tiago-pereira** [animapp-dev/animapp#36]
What if we add a linter? Code style could be maintained and commits of that kind would be avoided.

Here's a [how to](https://github.com/verekia/js-stack-from-scratch/blob/master/tutorial/02-babel-es6-eslint-flow-jest-husky.md#eslint), what do you think? 
[Travis](https://travis-ci.org/) could also guarantee that the linter is being executed.

@mblodorn @fsgoertmann

**Comment by mblodorn** [comment]
I think it is a great idea! Check this out @fsgoertmann, @tiagodws

**Comment by mblodorn** [comment]
Both are done!
